import { UserProfile } from './types';

export const AVATAR_LIST = [
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195442/quizmaster_avatars/1.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195451/quizmaster_avatars/2.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195459/quizmaster_avatars/3.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195460/quizmaster_avatars/4.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195461/quizmaster_avatars/5.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195461/quizmaster_avatars/6.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195462/quizmaster_avatars/7.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195463/quizmaster_avatars/8.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195463/quizmaster_avatars/9.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195443/quizmaster_avatars/10.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195444/quizmaster_avatars/11.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195445/quizmaster_avatars/12.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195446/quizmaster_avatars/13.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195446/quizmaster_avatars/14.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195447/quizmaster_avatars/15.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195448/quizmaster_avatars/16.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195449/quizmaster_avatars/17.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195449/quizmaster_avatars/18.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195450/quizmaster_avatars/19.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195452/quizmaster_avatars/20.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195453/quizmaster_avatars/21.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195453/quizmaster_avatars/22.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195454/quizmaster_avatars/23.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195455/quizmaster_avatars/24.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195455/quizmaster_avatars/25.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195456/quizmaster_avatars/26.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195457/quizmaster_avatars/27.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195458/quizmaster_avatars/28.png",
  "https://res.cloudinary.com/dqixbzrvd/image/upload/v1777195458/quizmaster_avatars/29.png"
];

export const DUMMY_USER: UserProfile = {
  name: "",
  username: "",
  email: "",
  phone: "",
  dob: "",
  location: {
    city: "",
    pinCode: "",
    state: "",
    country: ""
  },
  avatarUrl: AVATAR_LIST[0],
  profilePicture: "",
  bio: "",
  skills: {
    languages: [],
    frameworks: [],
    databases: [],
    tools: [],
  },
  education: {
    collegeName: "",
    branch: "",
    graduationYear: "",
    degree: "",
    currentRole: "",
  },
  socialLinks: {
    github: "",
    linkedin: "",
    twitter: "",
    others: "",
    resume: "",
  },
  codingProfiles: {
    leetcode: "",
    hackerrank: "",
    codeforces: "",
    geeksforgeeks: "",
    others: "",
  },
  workExperience: [],
  projects: [],
  streak: 0,
};
